# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'InteTry' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for InteTry
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # needed for debugging
    # Add any other subspecs you want to use in your project
  ]

  # only for React Native ^0.39.[0-2] afaik
  # def patch_csslayout(installer)
  #   version = `node -p -e "require('../node_modules/react-native/package.json').version"`

  #   # unless version =~ /^0\.39\.[0-2]$/
  #   #   puts ">> Unsure if I should patch for CSSLayout on React Native #{version}. Skipping."
  #   #   return
  #   # end

  #   puts ">> Patching for CSSLayout on React Native #{version}"

  #   # patch header files
  #   # https://github.com/facebook/react-native/issues/11272
  #   `find ../node_modules/react-native \\( -name *.h -o -name *.m \\) -print0 | xargs -0 sed -i '' -e 's:<CSSLayout/\\(.*\\)>:"\\1":g'`

  #   # exclude duplicate symbols
  #   # https://github.com/facebook/react-native/issues/11502
  #   installer.pods_project.targets.each do |target|
  #     next unless target.name == 'React'

  #     source_files = target.source_build_phase.files
  #     uniqs = source_files.uniq { |f| f.file_ref.path }
  #     (source_files - uniqs).each { |dup| source_files.delete(dup) }
  #   end
  # end

  # post_install do |installer|
  #   patch_csslayout(installer)
  # end

  # pre_install do |installer|
  #     # Yoga exists in two places in the RN source tree. Delete the obsolete one to avoid redefinitions
  #     `rm -rf ../node_modules/react-native/React/CSSLayout`
  # end

  # post_install do |installer|
  #     patch_subspecs(installer)
  # end

  # def patch_subspecs(installer)
  #     # patch source and header files
  #     `find ../node_modules/react-native/React ../node_modules/react-native/ReactCommon \\( -name *.h -o -name *.m -o -name *.mm \\) -print0 | xargs -0 sed -i '' -E 's:<(yoga|jschelpers|cxxreact)/(.*)>:"\\2":g'`

  #     # exclude duplicate symbols
  #     # https://github.com/facebook/react-native/issues/11502
  #     installer.pods_project.targets.each do |target|
  #         next unless target.name == 'React'

  #         source_files = target.source_build_phase.files
  #         uniqs = source_files.uniq { |f| f.file_ref.path }
  #         (source_files - uniqs).each { |dup| source_files.delete(dup) }
  #     end
  # end

end
