# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'InteTry' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for InteTry
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
      'RCTText',
      'RCTImage',
      'RCTWebSocket', # needed for debugging
      'RCTNetwork',
      'RCTLinkingIOS', # dependency of react-native-router-flux
      'RCTAnimation', # require by useNativeDriver
      'RCTCameraRoll',
      'RCTActionSheet',
      'RCTGeolocation',
  ]
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

end
